/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.person.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.systems.dipe.srs.person.jooq.tables.JContact;

import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JContactRecord extends UpdatableRecordImpl<JContactRecord> implements Record5<UUID, UUID, String, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>people.contact.contact_id</code>.
     */
    public JContactRecord setContactId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>people.contact.contact_id</code>.
     */
    public UUID getContactId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>people.contact.person_id</code>.
     */
    public JContactRecord setPersonId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>people.contact.person_id</code>.
     */
    public UUID getPersonId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>people.contact.phone</code>.
     */
    public JContactRecord setPhone(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>people.contact.phone</code>.
     */
    public String getPhone() {
        return (String) get(2);
    }

    /**
     * Setter for <code>people.contact.email</code>.
     */
    public JContactRecord setEmail(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>people.contact.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>people.contact.created</code>.
     */
    public JContactRecord setCreated(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>people.contact.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, UUID, String, String, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UUID, UUID, String, String, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return JContact.CONTACT.CONTACT_ID;
    }

    @Override
    public Field<UUID> field2() {
        return JContact.CONTACT.PERSON_ID;
    }

    @Override
    public Field<String> field3() {
        return JContact.CONTACT.PHONE;
    }

    @Override
    public Field<String> field4() {
        return JContact.CONTACT.EMAIL;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return JContact.CONTACT.CREATED;
    }

    @Override
    public UUID component1() {
        return getContactId();
    }

    @Override
    public UUID component2() {
        return getPersonId();
    }

    @Override
    public String component3() {
        return getPhone();
    }

    @Override
    public String component4() {
        return getEmail();
    }

    @Override
    public LocalDateTime component5() {
        return getCreated();
    }

    @Override
    public UUID value1() {
        return getContactId();
    }

    @Override
    public UUID value2() {
        return getPersonId();
    }

    @Override
    public String value3() {
        return getPhone();
    }

    @Override
    public String value4() {
        return getEmail();
    }

    @Override
    public LocalDateTime value5() {
        return getCreated();
    }

    @Override
    public JContactRecord value1(UUID value) {
        setContactId(value);
        return this;
    }

    @Override
    public JContactRecord value2(UUID value) {
        setPersonId(value);
        return this;
    }

    @Override
    public JContactRecord value3(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public JContactRecord value4(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public JContactRecord value5(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public JContactRecord values(UUID value1, UUID value2, String value3, String value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JContactRecord
     */
    public JContactRecord() {
        super(JContact.CONTACT);
    }

    /**
     * Create a detached, initialised JContactRecord
     */
    public JContactRecord(UUID contactId, UUID personId, String phone, String email, LocalDateTime created) {
        super(JContact.CONTACT);

        setContactId(contactId);
        setPersonId(personId);
        setPhone(phone);
        setEmail(email);
        setCreated(created);
    }
}
