/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.person.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.systems.dipe.srs.person.jooq.tables.JIdentification;

import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JIdentificationRecord extends UpdatableRecordImpl<JIdentificationRecord> implements Record4<String, String, UUID, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>people.identification.identity_id</code>.
     */
    public JIdentificationRecord setIdentityId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>people.identification.identity_id</code>.
     */
    public String getIdentityId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>people.identification.identity_type</code>.
     */
    public JIdentificationRecord setIdentityType(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>people.identification.identity_type</code>.
     */
    public String getIdentityType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>people.identification.person_id</code>.
     */
    public JIdentificationRecord setPersonId(UUID value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>people.identification.person_id</code>.
     */
    public UUID getPersonId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>people.identification.created</code>.
     */
    public JIdentificationRecord setCreated(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>people.identification.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, UUID, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, UUID, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return JIdentification.IDENTIFICATION.IDENTITY_ID;
    }

    @Override
    public Field<String> field2() {
        return JIdentification.IDENTIFICATION.IDENTITY_TYPE;
    }

    @Override
    public Field<UUID> field3() {
        return JIdentification.IDENTIFICATION.PERSON_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return JIdentification.IDENTIFICATION.CREATED;
    }

    @Override
    public String component1() {
        return getIdentityId();
    }

    @Override
    public String component2() {
        return getIdentityType();
    }

    @Override
    public UUID component3() {
        return getPersonId();
    }

    @Override
    public LocalDateTime component4() {
        return getCreated();
    }

    @Override
    public String value1() {
        return getIdentityId();
    }

    @Override
    public String value2() {
        return getIdentityType();
    }

    @Override
    public UUID value3() {
        return getPersonId();
    }

    @Override
    public LocalDateTime value4() {
        return getCreated();
    }

    @Override
    public JIdentificationRecord value1(String value) {
        setIdentityId(value);
        return this;
    }

    @Override
    public JIdentificationRecord value2(String value) {
        setIdentityType(value);
        return this;
    }

    @Override
    public JIdentificationRecord value3(UUID value) {
        setPersonId(value);
        return this;
    }

    @Override
    public JIdentificationRecord value4(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public JIdentificationRecord values(String value1, String value2, UUID value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JIdentificationRecord
     */
    public JIdentificationRecord() {
        super(JIdentification.IDENTIFICATION);
    }

    /**
     * Create a detached, initialised JIdentificationRecord
     */
    public JIdentificationRecord(String identityId, String identityType, UUID personId, LocalDateTime created) {
        super(JIdentification.IDENTIFICATION);

        setIdentityId(identityId);
        setIdentityType(identityType);
        setPersonId(personId);
        setCreated(created);
    }
}
