/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.person.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.systems.dipe.srs.person.jooq.tables.JPerson;

import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JPersonRecord extends UpdatableRecordImpl<JPersonRecord> implements Record4<UUID, String, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>people.person.person_id</code>.
     */
    public JPersonRecord setPersonId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>people.person.person_id</code>.
     */
    public UUID getPersonId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>people.person.first_name</code>.
     */
    public JPersonRecord setFirstName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>people.person.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>people.person.last_name</code>.
     */
    public JPersonRecord setLastName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>people.person.last_name</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>people.person.created</code>.
     */
    public JPersonRecord setCreated(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>people.person.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<UUID, String, String, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<UUID, String, String, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return JPerson.PERSON.PERSON_ID;
    }

    @Override
    public Field<String> field2() {
        return JPerson.PERSON.FIRST_NAME;
    }

    @Override
    public Field<String> field3() {
        return JPerson.PERSON.LAST_NAME;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return JPerson.PERSON.CREATED;
    }

    @Override
    public UUID component1() {
        return getPersonId();
    }

    @Override
    public String component2() {
        return getFirstName();
    }

    @Override
    public String component3() {
        return getLastName();
    }

    @Override
    public LocalDateTime component4() {
        return getCreated();
    }

    @Override
    public UUID value1() {
        return getPersonId();
    }

    @Override
    public String value2() {
        return getFirstName();
    }

    @Override
    public String value3() {
        return getLastName();
    }

    @Override
    public LocalDateTime value4() {
        return getCreated();
    }

    @Override
    public JPersonRecord value1(UUID value) {
        setPersonId(value);
        return this;
    }

    @Override
    public JPersonRecord value2(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public JPersonRecord value3(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public JPersonRecord value4(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public JPersonRecord values(UUID value1, String value2, String value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JPersonRecord
     */
    public JPersonRecord() {
        super(JPerson.PERSON);
    }

    /**
     * Create a detached, initialised JPersonRecord
     */
    public JPersonRecord(UUID personId, String firstName, String lastName, LocalDateTime created) {
        super(JPerson.PERSON);

        setPersonId(personId);
        setFirstName(firstName);
        setLastName(lastName);
        setCreated(created);
    }
}
