/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.inventory.jooq;


import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.systems.dipe.srs.inventory.jooq.tables.JInventory;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JInventories extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>inventories</code>
     */
    public static final JInventories INVENTORIES = new JInventories();

    /**
     * The table <code>inventories.inventory</code>.
     */
    public final JInventory INVENTORY = JInventory.INVENTORY;

    /**
     * No further instances allowed
     */
    private JInventories() {
        super("inventories", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            JInventory.INVENTORY
        );
    }
}
