/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.inventory.jooq;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.systems.dipe.srs.inventory.jooq.tables.JInventory;
import org.systems.dipe.srs.inventory.jooq.tables.records.JInventoryRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * inventories.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<JInventoryRecord> PK_INVENTORIES_INVENTORY = Internal.createUniqueKey(JInventory.INVENTORY, DSL.name("PK.inventories.inventory"), new TableField[] { JInventory.INVENTORY.INVENTORY_ID }, true);
}
