/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.inventory.jooq;


import org.systems.dipe.srs.inventory.jooq.tables.JInventory;


/**
 * Convenience access to all tables in inventories.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>inventories.inventory</code>.
     */
    public static final JInventory INVENTORY = JInventory.INVENTORY;
}
