/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.squad.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.systems.dipe.srs.squad.jooq.tables.JEquipment;

import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JEquipmentRecord extends UpdatableRecordImpl<JEquipmentRecord> implements Record3<UUID, UUID, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>squads.equipment.inventory_id</code>.
     */
    public JEquipmentRecord setInventoryId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>squads.equipment.inventory_id</code>.
     */
    public UUID getInventoryId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>squads.equipment.squad_id</code>.
     */
    public JEquipmentRecord setSquadId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>squads.equipment.squad_id</code>.
     */
    public UUID getSquadId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>squads.equipment.created</code>.
     */
    public JEquipmentRecord setCreated(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>squads.equipment.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, UUID, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, UUID, LocalDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return JEquipment.EQUIPMENT.INVENTORY_ID;
    }

    @Override
    public Field<UUID> field2() {
        return JEquipment.EQUIPMENT.SQUAD_ID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return JEquipment.EQUIPMENT.CREATED;
    }

    @Override
    public UUID component1() {
        return getInventoryId();
    }

    @Override
    public UUID component2() {
        return getSquadId();
    }

    @Override
    public LocalDateTime component3() {
        return getCreated();
    }

    @Override
    public UUID value1() {
        return getInventoryId();
    }

    @Override
    public UUID value2() {
        return getSquadId();
    }

    @Override
    public LocalDateTime value3() {
        return getCreated();
    }

    @Override
    public JEquipmentRecord value1(UUID value) {
        setInventoryId(value);
        return this;
    }

    @Override
    public JEquipmentRecord value2(UUID value) {
        setSquadId(value);
        return this;
    }

    @Override
    public JEquipmentRecord value3(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public JEquipmentRecord values(UUID value1, UUID value2, LocalDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JEquipmentRecord
     */
    public JEquipmentRecord() {
        super(JEquipment.EQUIPMENT);
    }

    /**
     * Create a detached, initialised JEquipmentRecord
     */
    public JEquipmentRecord(UUID inventoryId, UUID squadId, LocalDateTime created) {
        super(JEquipment.EQUIPMENT);

        setInventoryId(inventoryId);
        setSquadId(squadId);
        setCreated(created);
    }
}
