/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.squad.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.systems.dipe.srs.squad.jooq.tables.JMember;

import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JMemberRecord extends UpdatableRecordImpl<JMemberRecord> implements Record5<UUID, UUID, UUID, Boolean, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>squads.member.member_id</code>.
     */
    public JMemberRecord setMemberId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>squads.member.member_id</code>.
     */
    public UUID getMemberId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>squads.member.squad_id</code>.
     */
    public JMemberRecord setSquadId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>squads.member.squad_id</code>.
     */
    public UUID getSquadId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>squads.member.volunteer_id</code>.
     */
    public JMemberRecord setVolunteerId(UUID value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>squads.member.volunteer_id</code>.
     */
    public UUID getVolunteerId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>squads.member.head</code>.
     */
    public JMemberRecord setHead(Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>squads.member.head</code>.
     */
    public Boolean getHead() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>squads.member.created</code>.
     */
    public JMemberRecord setCreated(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>squads.member.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, UUID, UUID, Boolean, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UUID, UUID, UUID, Boolean, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return JMember.MEMBER.MEMBER_ID;
    }

    @Override
    public Field<UUID> field2() {
        return JMember.MEMBER.SQUAD_ID;
    }

    @Override
    public Field<UUID> field3() {
        return JMember.MEMBER.VOLUNTEER_ID;
    }

    @Override
    public Field<Boolean> field4() {
        return JMember.MEMBER.HEAD;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return JMember.MEMBER.CREATED;
    }

    @Override
    public UUID component1() {
        return getMemberId();
    }

    @Override
    public UUID component2() {
        return getSquadId();
    }

    @Override
    public UUID component3() {
        return getVolunteerId();
    }

    @Override
    public Boolean component4() {
        return getHead();
    }

    @Override
    public LocalDateTime component5() {
        return getCreated();
    }

    @Override
    public UUID value1() {
        return getMemberId();
    }

    @Override
    public UUID value2() {
        return getSquadId();
    }

    @Override
    public UUID value3() {
        return getVolunteerId();
    }

    @Override
    public Boolean value4() {
        return getHead();
    }

    @Override
    public LocalDateTime value5() {
        return getCreated();
    }

    @Override
    public JMemberRecord value1(UUID value) {
        setMemberId(value);
        return this;
    }

    @Override
    public JMemberRecord value2(UUID value) {
        setSquadId(value);
        return this;
    }

    @Override
    public JMemberRecord value3(UUID value) {
        setVolunteerId(value);
        return this;
    }

    @Override
    public JMemberRecord value4(Boolean value) {
        setHead(value);
        return this;
    }

    @Override
    public JMemberRecord value5(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public JMemberRecord values(UUID value1, UUID value2, UUID value3, Boolean value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JMemberRecord
     */
    public JMemberRecord() {
        super(JMember.MEMBER);
    }

    /**
     * Create a detached, initialised JMemberRecord
     */
    public JMemberRecord(UUID memberId, UUID squadId, UUID volunteerId, Boolean head, LocalDateTime created) {
        super(JMember.MEMBER);

        setMemberId(memberId);
        setSquadId(squadId);
        setVolunteerId(volunteerId);
        setHead(head);
        setCreated(created);
    }
}
