/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.search.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.systems.dipe.srs.search.jooq.tables.JSearchLocation;
import org.systems.dipe.srs.search.jooq.tables.JSearchSquad;


/**
 * A class modelling indexes of tables in searches.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IX_SEARCHES_SEARCH_LOCATION_LOCATION_PROCESS = Internal.createIndex(DSL.name("IX_searches.search_location.location_process"), JSearchLocation.SEARCH_LOCATION, new OrderField[] { JSearchLocation.SEARCH_LOCATION.LOCATION_ID, JSearchLocation.SEARCH_LOCATION.PROCESS_ID }, true);
    public static final Index IX_SEARCHES_SEARCH_SQUAD_SQUAD_PROCESS = Internal.createIndex(DSL.name("IX_searches.search_squad.squad_process"), JSearchSquad.SEARCH_SQUAD, new OrderField[] { JSearchSquad.SEARCH_SQUAD.SQUAD_ID, JSearchSquad.SEARCH_SQUAD.PROCESS_ID }, true);
}
