/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.search.jooq;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.systems.dipe.srs.search.jooq.tables.JSearchLocation;
import org.systems.dipe.srs.search.jooq.tables.JSearchProcess;
import org.systems.dipe.srs.search.jooq.tables.JSearchSquad;
import org.systems.dipe.srs.search.jooq.tables.records.JSearchLocationRecord;
import org.systems.dipe.srs.search.jooq.tables.records.JSearchProcessRecord;
import org.systems.dipe.srs.search.jooq.tables.records.JSearchSquadRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * searches.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<JSearchLocationRecord> PK_SEARCHES_SEARCH_LOCATION = Internal.createUniqueKey(JSearchLocation.SEARCH_LOCATION, DSL.name("PK.searches.search_location"), new TableField[] { JSearchLocation.SEARCH_LOCATION.LOCATION_ID }, true);
    public static final UniqueKey<JSearchProcessRecord> PK_SEARCHES_SEARCH_PROCESS = Internal.createUniqueKey(JSearchProcess.SEARCH_PROCESS, DSL.name("PK.searches.search_process"), new TableField[] { JSearchProcess.SEARCH_PROCESS.PROCESS_ID }, true);
    public static final UniqueKey<JSearchSquadRecord> PK_SEARCHES_SEARCH_SQUAD = Internal.createUniqueKey(JSearchSquad.SEARCH_SQUAD, DSL.name("PK.searches.search_squad"), new TableField[] { JSearchSquad.SEARCH_SQUAD.SQUAD_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<JSearchLocationRecord, JSearchProcessRecord> SEARCH_LOCATION__FK_SEARCHES_SEARCH_LOCATION_PROCESS = Internal.createForeignKey(JSearchLocation.SEARCH_LOCATION, DSL.name("FK.searches.search_location.process"), new TableField[] { JSearchLocation.SEARCH_LOCATION.PROCESS_ID }, Keys.PK_SEARCHES_SEARCH_PROCESS, new TableField[] { JSearchProcess.SEARCH_PROCESS.PROCESS_ID }, true);
    public static final ForeignKey<JSearchSquadRecord, JSearchProcessRecord> SEARCH_SQUAD__FK_SEARCHES_SEARCH_SQUAD_PROCESS = Internal.createForeignKey(JSearchSquad.SEARCH_SQUAD, DSL.name("FK.searches.search_squad.process"), new TableField[] { JSearchSquad.SEARCH_SQUAD.PROCESS_ID }, Keys.PK_SEARCHES_SEARCH_PROCESS, new TableField[] { JSearchProcess.SEARCH_PROCESS.PROCESS_ID }, true);
}
