/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.search.jooq;


import org.systems.dipe.srs.search.jooq.tables.JSearchLocation;
import org.systems.dipe.srs.search.jooq.tables.JSearchProcess;
import org.systems.dipe.srs.search.jooq.tables.JSearchSquad;


/**
 * Convenience access to all tables in searches.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>searches.search_location</code>.
     */
    public static final JSearchLocation SEARCH_LOCATION = JSearchLocation.SEARCH_LOCATION;

    /**
     * The table <code>searches.search_process</code>.
     */
    public static final JSearchProcess SEARCH_PROCESS = JSearchProcess.SEARCH_PROCESS;

    /**
     * The table <code>searches.search_squad</code>.
     */
    public static final JSearchSquad SEARCH_SQUAD = JSearchSquad.SEARCH_SQUAD;
}
