/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.squad.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.systems.dipe.srs.squad.jooq.tables.JEquipment;


/**
 * A class modelling indexes of tables in squads.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IX_SQUADS_EQUIPMENT_INVENTORY_SQUAD = Internal.createIndex(DSL.name("IX_squads.equipment.inventory_squad"), JEquipment.EQUIPMENT, new OrderField[] { JEquipment.EQUIPMENT.INVENTORY_ID, JEquipment.EQUIPMENT.SQUAD_ID }, true);
}
