/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.squad.jooq;


import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.systems.dipe.srs.squad.jooq.tables.JEquipment;
import org.systems.dipe.srs.squad.jooq.tables.JMember;
import org.systems.dipe.srs.squad.jooq.tables.JSquad;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JSquads extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>squads</code>
     */
    public static final JSquads SQUADS = new JSquads();

    /**
     * The table <code>squads.equipment</code>.
     */
    public final JEquipment EQUIPMENT = JEquipment.EQUIPMENT;

    /**
     * The table <code>squads.member</code>.
     */
    public final JMember MEMBER = JMember.MEMBER;

    /**
     * The table <code>squads.squad</code>.
     */
    public final JSquad SQUAD = JSquad.SQUAD;

    /**
     * No further instances allowed
     */
    private JSquads() {
        super("squads", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            JEquipment.EQUIPMENT,
            JMember.MEMBER,
            JSquad.SQUAD
        );
    }
}
