/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.squad.jooq;


import org.systems.dipe.srs.squad.jooq.tables.JEquipment;
import org.systems.dipe.srs.squad.jooq.tables.JMember;
import org.systems.dipe.srs.squad.jooq.tables.JSquad;


/**
 * Convenience access to all tables in squads.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>squads.equipment</code>.
     */
    public static final JEquipment EQUIPMENT = JEquipment.EQUIPMENT;

    /**
     * The table <code>squads.member</code>.
     */
    public static final JMember MEMBER = JMember.MEMBER;

    /**
     * The table <code>squads.squad</code>.
     */
    public static final JSquad SQUAD = JSquad.SQUAD;
}
