/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.location.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.systems.dipe.srs.location.jooq.tables.JComment;


/**
 * A class modelling indexes of tables in locations.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IX_LOCATIONS_COMMENT_AUTHOR = Internal.createIndex(DSL.name("IX_locations.comment.author"), JComment.COMMENT, new OrderField[] { JComment.COMMENT.AUTHOR_ID }, false);
}
