/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.location.jooq;


import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.systems.dipe.srs.location.jooq.tables.JComment;
import org.systems.dipe.srs.location.jooq.tables.JLocation;
import org.systems.dipe.srs.location.jooq.tables.JPoint;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JLocations extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>locations</code>
     */
    public static final JLocations LOCATIONS = new JLocations();

    /**
     * The table <code>locations.comment</code>.
     */
    public final JComment COMMENT = JComment.COMMENT;

    /**
     * The table <code>locations.location</code>.
     */
    public final JLocation LOCATION = JLocation.LOCATION;

    /**
     * The table <code>locations.point</code>.
     */
    public final JPoint POINT = JPoint.POINT;

    /**
     * No further instances allowed
     */
    private JLocations() {
        super("locations", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            JComment.COMMENT,
            JLocation.LOCATION,
            JPoint.POINT
        );
    }
}
