/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.location.jooq;


import org.systems.dipe.srs.location.jooq.tables.JComment;
import org.systems.dipe.srs.location.jooq.tables.JLocation;
import org.systems.dipe.srs.location.jooq.tables.JPoint;


/**
 * Convenience access to all tables in locations.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>locations.comment</code>.
     */
    public static final JComment COMMENT = JComment.COMMENT;

    /**
     * The table <code>locations.location</code>.
     */
    public static final JLocation LOCATION = JLocation.LOCATION;

    /**
     * The table <code>locations.point</code>.
     */
    public static final JPoint POINT = JPoint.POINT;
}
