version: '2'

services:

  postgresql:
    container_name: srs-postgresql
    hostname: ${POSTGRES_HOST}
    image: postgres:${POSTGRES_VERSION}
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgresql:/var/lib/postgresql/data/
    networks:
      - srs-platform

  rabbitmq:
    container_name: srs-rabbitmq
    hostname: ${RABBITMQ_HOST}
    image: rabbitmq:${RABBITMQ_VERSION}
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
#      - 25672:25672
      - ${RABBITMQ_MNG_PORT}:15672
#      - 4369:4369
#      - 5671:5671
      - ${RABBITMQ_PORT}:5672
    networks:
      - srs-platform

volumes:
  postgresql:
    driver: local

networks:
  srs-platform:
    driver: bridge