version: '2'

services:

  postgresql:
    container_name: srs-postgresql
    hostname: ${POSTGRES_HOST}
    image: postgres:${POSTGRES_VERSION}
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgresql:/var/lib/postgresql/data/
    networks:
      - srs-platform

volumes:
  postgresql:
    driver: local

networks:
  srs-platform:
    driver: bridge