/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.person.jooq;


import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.systems.dipe.srs.person.jooq.tables.*;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JPeople extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>people</code>
     */
    public static final JPeople PEOPLE = new JPeople();

    /**
     * The table <code>people.contact</code>.
     */
    public final JContact CONTACT = JContact.CONTACT;

    /**
     * The table <code>people.identification</code>.
     */
    public final JIdentification IDENTIFICATION = JIdentification.IDENTIFICATION;

    /**
     * The table <code>people.person</code>.
     */
    public final JPerson PERSON = JPerson.PERSON;

    /**
     * The table <code>people.role</code>.
     */
    public final JRole ROLE = JRole.ROLE;

    /**
     * The table <code>people.role_link</code>.
     */
    public final JRoleLink ROLE_LINK = JRoleLink.ROLE_LINK;

    /**
     * No further instances allowed
     */
    private JPeople() {
        super("people", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            JContact.CONTACT,
            JIdentification.IDENTIFICATION,
            JPerson.PERSON,
            JRole.ROLE,
            JRoleLink.ROLE_LINK
        );
    }
}
