/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.person.jooq;


import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.systems.dipe.srs.person.jooq.tables.JContact;
import org.systems.dipe.srs.person.jooq.tables.JPerson;
import org.systems.dipe.srs.person.jooq.tables.JRole;
import org.systems.dipe.srs.person.jooq.tables.JRoleLink;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JSrsPerson extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>srs_person</code>
     */
    public static final JSrsPerson SRS_PERSON = new JSrsPerson();

    /**
     * The table <code>srs_person.contact</code>.
     */
    public final JContact CONTACT = JContact.CONTACT;

    /**
     * The table <code>srs_person.person</code>.
     */
    public final JPerson PERSON = JPerson.PERSON;

    /**
     * The table <code>srs_person.role</code>.
     */
    public final JRole ROLE = JRole.ROLE;

    /**
     * The table <code>srs_person.role_link</code>.
     */
    public final JRoleLink ROLE_LINK = JRoleLink.ROLE_LINK;

    /**
     * No further instances allowed
     */
    private JSrsPerson() {
        super("srs_person", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            JContact.CONTACT,
            JPerson.PERSON,
            JRole.ROLE,
            JRoleLink.ROLE_LINK
        );
    }
}
