/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.person.jooq;


import org.systems.dipe.srs.person.jooq.tables.JContact;
import org.systems.dipe.srs.person.jooq.tables.JPerson;
import org.systems.dipe.srs.person.jooq.tables.JRole;
import org.systems.dipe.srs.person.jooq.tables.JRoleLink;


/**
 * Convenience access to all tables in srs_person.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>srs_person.contact</code>.
     */
    public static final JContact CONTACT = JContact.CONTACT;

    /**
     * The table <code>srs_person.person</code>.
     */
    public static final JPerson PERSON = JPerson.PERSON;

    /**
     * The table <code>srs_person.role</code>.
     */
    public static final JRole ROLE = JRole.ROLE;

    /**
     * The table <code>srs_person.role_link</code>.
     */
    public static final JRoleLink ROLE_LINK = JRoleLink.ROLE_LINK;
}
