spring:
  application:
    name: srs-core-platform
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
  rabbitmq:
    virtual-host: /

logging:
  level:
    root: INFO
    org.jooq.Constants: OFF
    org.systems.dipe: DEBUG
  config: classpath:logback.xml