spring:
  application:
    name: srs-platform
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
  rabbitmq:
    virtual-host: /
  jackson:
    default-property-inclusion: non_null


logging:
  level:
    root: INFO
    org.jooq.Constants: OFF
    org.systems.dipe: DEBUG
  config: classpath:logback.xml