/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.person.jooq.tables;


import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.systems.dipe.srs.person.jooq.Indexes;
import org.systems.dipe.srs.person.jooq.JSrsPeople;
import org.systems.dipe.srs.person.jooq.Keys;
import org.systems.dipe.srs.person.jooq.tables.records.JRoleLinkRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JRoleLink extends TableImpl<JRoleLinkRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>srs_people.role_link</code>
     */
    public static final JRoleLink ROLE_LINK = new JRoleLink();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JRoleLinkRecord> getRecordType() {
        return JRoleLinkRecord.class;
    }

    /**
     * The column <code>srs_people.role_link.role_id</code>.
     */
    public final TableField<JRoleLinkRecord, UUID> ROLE_ID = createField(DSL.name("role_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>srs_people.role_link.person_id</code>.
     */
    public final TableField<JRoleLinkRecord, UUID> PERSON_ID = createField(DSL.name("person_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>srs_people.role_link.created</code>.
     */
    public final TableField<JRoleLinkRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "");

    private JRoleLink(Name alias, Table<JRoleLinkRecord> aliased) {
        this(alias, aliased, null);
    }

    private JRoleLink(Name alias, Table<JRoleLinkRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>srs_people.role_link</code> table reference
     */
    public JRoleLink(String alias) {
        this(DSL.name(alias), ROLE_LINK);
    }

    /**
     * Create an aliased <code>srs_people.role_link</code> table reference
     */
    public JRoleLink(Name alias) {
        this(alias, ROLE_LINK);
    }

    /**
     * Create a <code>srs_people.role_link</code> table reference
     */
    public JRoleLink() {
        this(DSL.name("role_link"), null);
    }

    public <O extends Record> JRoleLink(Table<O> child, ForeignKey<O, JRoleLinkRecord> key) {
        super(child, key, ROLE_LINK);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JSrsPeople.SRS_PEOPLE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IX_SRS_PEOPLE_ROLE_LINK_ROLE_PERSON);
    }

    @Override
    public List<ForeignKey<JRoleLinkRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ROLE_LINK__FK_SRS_PEOPLE_ROLE_LINK_ROLE, Keys.ROLE_LINK__FK_SRS_PEOPLE_ROLE_LINK_PERSON);
    }

    private transient JRole _role;
    private transient JPerson _person;

    /**
     * Get the implicit join path to the <code>srs_people.role</code> table.
     */
    public JRole role() {
        if (_role == null)
            _role = new JRole(this, Keys.ROLE_LINK__FK_SRS_PEOPLE_ROLE_LINK_ROLE);

        return _role;
    }

    /**
     * Get the implicit join path to the <code>srs_people.person</code> table.
     */
    public JPerson person() {
        if (_person == null)
            _person = new JPerson(this, Keys.ROLE_LINK__FK_SRS_PEOPLE_ROLE_LINK_PERSON);

        return _person;
    }

    @Override
    public JRoleLink as(String alias) {
        return new JRoleLink(DSL.name(alias), this);
    }

    @Override
    public JRoleLink as(Name alias) {
        return new JRoleLink(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JRoleLink rename(String name) {
        return new JRoleLink(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JRoleLink rename(Name name) {
        return new JRoleLink(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, UUID, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
