/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.orchestration;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.systems.dipe.srs.orchestration.tables.JEvent;


/**
 * A class modelling indexes of tables in orchestration.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IX_ORCHESTRATION_EVENT_RETRY = Internal.createIndex(DSL.name("IX_orchestration.event.retry"), JEvent.EVENT, new OrderField[] { JEvent.EVENT.RETRY_AT, JEvent.EVENT.STATUS }, false);
    public static final Index IX_ORCHESTRATION_EVENT_STATUS = Internal.createIndex(DSL.name("IX_orchestration.event.status"), JEvent.EVENT, new OrderField[] { JEvent.EVENT.STATUS }, false);
}
