/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.orchestration;


import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.systems.dipe.srs.orchestration.tables.JEvent;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JOrchestration extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>orchestration</code>
     */
    public static final JOrchestration ORCHESTRATION = new JOrchestration();

    /**
     * The table <code>orchestration.event</code>.
     */
    public final JEvent EVENT = JEvent.EVENT;

    /**
     * No further instances allowed
     */
    private JOrchestration() {
        super("orchestration", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            JEvent.EVENT
        );
    }
}
