/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.orchestration;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.systems.dipe.srs.orchestration.tables.JEvent;
import org.systems.dipe.srs.orchestration.tables.records.JEventRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * orchestration.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<JEventRecord> PK_ORCHESTRATION_EVENT = Internal.createUniqueKey(JEvent.EVENT, DSL.name("PK.orchestration.event"), new TableField[] { JEvent.EVENT.EVENT_ID }, true);
}
