/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.orchestration;


import org.systems.dipe.srs.orchestration.tables.JEvent;


/**
 * Convenience access to all tables in orchestration.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>orchestration.event</code>.
     */
    public static final JEvent EVENT = JEvent.EVENT;
}
