/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.request.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.systems.dipe.srs.request.jooq.tables.JRequest;
import org.systems.dipe.srs.request.jooq.tables.JRequestLocation;


/**
 * A class modelling indexes of tables in requests.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IX_REQUESTS_REQUEST_CUSTOMER = Internal.createIndex(DSL.name("IX_requests.request.customer"), JRequest.REQUEST, new OrderField[] { JRequest.REQUEST.CUSTOMER_ID }, false);
    public static final Index IX_REQUESTS_REQUEST_SUPERVISOR = Internal.createIndex(DSL.name("IX_requests.request.supervisor"), JRequest.REQUEST, new OrderField[] { JRequest.REQUEST.SUPERVISOR_ID }, false);
    public static final Index IX_REQUESTS_REQUEST_LOCATION_LOCATION_REQUEST = Internal.createIndex(DSL.name("IX_requests.request_location.location_request"), JRequestLocation.REQUEST_LOCATION, new OrderField[] { JRequestLocation.REQUEST_LOCATION.LOCATION_ID, JRequestLocation.REQUEST_LOCATION.REQUEST_ID }, true);
}
