/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.request.jooq;


import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.systems.dipe.srs.request.jooq.tables.JRequest;
import org.systems.dipe.srs.request.jooq.tables.JRequestItem;
import org.systems.dipe.srs.request.jooq.tables.JRequestLocation;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JRequests extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>requests</code>
     */
    public static final JRequests REQUESTS = new JRequests();

    /**
     * The table <code>requests.request</code>.
     */
    public final JRequest REQUEST = JRequest.REQUEST;

    /**
     * The table <code>requests.request_item</code>.
     */
    public final JRequestItem REQUEST_ITEM = JRequestItem.REQUEST_ITEM;

    /**
     * The table <code>requests.request_location</code>.
     */
    public final JRequestLocation REQUEST_LOCATION = JRequestLocation.REQUEST_LOCATION;

    /**
     * No further instances allowed
     */
    private JRequests() {
        super("requests", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            JRequest.REQUEST,
            JRequestItem.REQUEST_ITEM,
            JRequestLocation.REQUEST_LOCATION
        );
    }
}
