/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.request.jooq;


import org.systems.dipe.srs.request.jooq.tables.JRequest;
import org.systems.dipe.srs.request.jooq.tables.JRequestItem;
import org.systems.dipe.srs.request.jooq.tables.JRequestLocation;


/**
 * Convenience access to all tables in requests.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>requests.request</code>.
     */
    public static final JRequest REQUEST = JRequest.REQUEST;

    /**
     * The table <code>requests.request_item</code>.
     */
    public static final JRequestItem REQUEST_ITEM = JRequestItem.REQUEST_ITEM;

    /**
     * The table <code>requests.request_location</code>.
     */
    public static final JRequestLocation REQUEST_LOCATION = JRequestLocation.REQUEST_LOCATION;
}
