/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.location.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.systems.dipe.srs.location.jooq.tables.JLocation;

import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JLocationRecord extends UpdatableRecordImpl<JLocationRecord> implements Record2<UUID, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>locations.location.location_id</code>.
     */
    public JLocationRecord setLocationId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>locations.location.location_id</code>.
     */
    public UUID getLocationId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>locations.location.created</code>.
     */
    public JLocationRecord setCreated(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>locations.location.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, LocalDateTime> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UUID, LocalDateTime> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return JLocation.LOCATION.LOCATION_ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return JLocation.LOCATION.CREATED;
    }

    @Override
    public UUID component1() {
        return getLocationId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreated();
    }

    @Override
    public UUID value1() {
        return getLocationId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreated();
    }

    @Override
    public JLocationRecord value1(UUID value) {
        setLocationId(value);
        return this;
    }

    @Override
    public JLocationRecord value2(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public JLocationRecord values(UUID value1, LocalDateTime value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JLocationRecord
     */
    public JLocationRecord() {
        super(JLocation.LOCATION);
    }

    /**
     * Create a detached, initialised JLocationRecord
     */
    public JLocationRecord(UUID locationId, LocalDateTime created) {
        super(JLocation.LOCATION);

        setLocationId(locationId);
        setCreated(created);
    }
}
