/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.location.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.systems.dipe.srs.location.jooq.tables.JPoint;

import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JPointRecord extends UpdatableRecordImpl<JPointRecord> implements Record5<UUID, UUID, Double, Double, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>locations.point.point_id</code>.
     */
    public JPointRecord setPointId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>locations.point.point_id</code>.
     */
    public UUID getPointId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>locations.point.location_id</code>.
     */
    public JPointRecord setLocationId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>locations.point.location_id</code>.
     */
    public UUID getLocationId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>locations.point.longitude</code>.
     */
    public JPointRecord setLongitude(Double value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>locations.point.longitude</code>.
     */
    public Double getLongitude() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>locations.point.latitude</code>.
     */
    public JPointRecord setLatitude(Double value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>locations.point.latitude</code>.
     */
    public Double getLatitude() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>locations.point.created</code>.
     */
    public JPointRecord setCreated(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>locations.point.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, UUID, Double, Double, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UUID, UUID, Double, Double, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return JPoint.POINT.POINT_ID;
    }

    @Override
    public Field<UUID> field2() {
        return JPoint.POINT.LOCATION_ID;
    }

    @Override
    public Field<Double> field3() {
        return JPoint.POINT.LONGITUDE;
    }

    @Override
    public Field<Double> field4() {
        return JPoint.POINT.LATITUDE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return JPoint.POINT.CREATED;
    }

    @Override
    public UUID component1() {
        return getPointId();
    }

    @Override
    public UUID component2() {
        return getLocationId();
    }

    @Override
    public Double component3() {
        return getLongitude();
    }

    @Override
    public Double component4() {
        return getLatitude();
    }

    @Override
    public LocalDateTime component5() {
        return getCreated();
    }

    @Override
    public UUID value1() {
        return getPointId();
    }

    @Override
    public UUID value2() {
        return getLocationId();
    }

    @Override
    public Double value3() {
        return getLongitude();
    }

    @Override
    public Double value4() {
        return getLatitude();
    }

    @Override
    public LocalDateTime value5() {
        return getCreated();
    }

    @Override
    public JPointRecord value1(UUID value) {
        setPointId(value);
        return this;
    }

    @Override
    public JPointRecord value2(UUID value) {
        setLocationId(value);
        return this;
    }

    @Override
    public JPointRecord value3(Double value) {
        setLongitude(value);
        return this;
    }

    @Override
    public JPointRecord value4(Double value) {
        setLatitude(value);
        return this;
    }

    @Override
    public JPointRecord value5(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public JPointRecord values(UUID value1, UUID value2, Double value3, Double value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JPointRecord
     */
    public JPointRecord() {
        super(JPoint.POINT);
    }

    /**
     * Create a detached, initialised JPointRecord
     */
    public JPointRecord(UUID pointId, UUID locationId, Double longitude, Double latitude, LocalDateTime created) {
        super(JPoint.POINT);

        setPointId(pointId);
        setLocationId(locationId);
        setLongitude(longitude);
        setLatitude(latitude);
        setCreated(created);
    }
}
