/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.location.jooq.tables;


import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.systems.dipe.srs.location.jooq.JLocations;
import org.systems.dipe.srs.location.jooq.Keys;
import org.systems.dipe.srs.location.jooq.tables.records.JLocationRecord;

import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JLocation extends TableImpl<JLocationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>locations.location</code>
     */
    public static final JLocation LOCATION = new JLocation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JLocationRecord> getRecordType() {
        return JLocationRecord.class;
    }

    /**
     * The column <code>locations.location.location_id</code>.
     */
    public final TableField<JLocationRecord, UUID> LOCATION_ID = createField(DSL.name("location_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>locations.location.created</code>.
     */
    public final TableField<JLocationRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field("now()", SQLDataType.LOCALDATETIME)), this, "");

    private JLocation(Name alias, Table<JLocationRecord> aliased) {
        this(alias, aliased, null);
    }

    private JLocation(Name alias, Table<JLocationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>locations.location</code> table reference
     */
    public JLocation(String alias) {
        this(DSL.name(alias), LOCATION);
    }

    /**
     * Create an aliased <code>locations.location</code> table reference
     */
    public JLocation(Name alias) {
        this(alias, LOCATION);
    }

    /**
     * Create a <code>locations.location</code> table reference
     */
    public JLocation() {
        this(DSL.name("location"), null);
    }

    public <O extends Record> JLocation(Table<O> child, ForeignKey<O, JLocationRecord> key) {
        super(child, key, LOCATION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JLocations.LOCATIONS;
    }

    @Override
    public UniqueKey<JLocationRecord> getPrimaryKey() {
        return Keys.PK_LOCATIONS_LOCATION;
    }

    @Override
    public JLocation as(String alias) {
        return new JLocation(DSL.name(alias), this);
    }

    @Override
    public JLocation as(Name alias) {
        return new JLocation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JLocation rename(String name) {
        return new JLocation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JLocation rename(Name name) {
        return new JLocation(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, LocalDateTime> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
