/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.search.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.systems.dipe.srs.search.jooq.tables.JSearchProcess;

import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JSearchProcessRecord extends UpdatableRecordImpl<JSearchProcessRecord> implements Record4<UUID, UUID, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>searches.search_process.process_id</code>.
     */
    public JSearchProcessRecord setProcessId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>searches.search_process.process_id</code>.
     */
    public UUID getProcessId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>searches.search_process.request_id</code>.
     */
    public JSearchProcessRecord setRequestId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>searches.search_process.request_id</code>.
     */
    public UUID getRequestId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>searches.search_process.status</code>.
     */
    public JSearchProcessRecord setStatus(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>searches.search_process.status</code>.
     */
    public String getStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>searches.search_process.created</code>.
     */
    public JSearchProcessRecord setCreated(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>searches.search_process.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<UUID, UUID, String, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<UUID, UUID, String, LocalDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return JSearchProcess.SEARCH_PROCESS.PROCESS_ID;
    }

    @Override
    public Field<UUID> field2() {
        return JSearchProcess.SEARCH_PROCESS.REQUEST_ID;
    }

    @Override
    public Field<String> field3() {
        return JSearchProcess.SEARCH_PROCESS.STATUS;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return JSearchProcess.SEARCH_PROCESS.CREATED;
    }

    @Override
    public UUID component1() {
        return getProcessId();
    }

    @Override
    public UUID component2() {
        return getRequestId();
    }

    @Override
    public String component3() {
        return getStatus();
    }

    @Override
    public LocalDateTime component4() {
        return getCreated();
    }

    @Override
    public UUID value1() {
        return getProcessId();
    }

    @Override
    public UUID value2() {
        return getRequestId();
    }

    @Override
    public String value3() {
        return getStatus();
    }

    @Override
    public LocalDateTime value4() {
        return getCreated();
    }

    @Override
    public JSearchProcessRecord value1(UUID value) {
        setProcessId(value);
        return this;
    }

    @Override
    public JSearchProcessRecord value2(UUID value) {
        setRequestId(value);
        return this;
    }

    @Override
    public JSearchProcessRecord value3(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public JSearchProcessRecord value4(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public JSearchProcessRecord values(UUID value1, UUID value2, String value3, LocalDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JSearchProcessRecord
     */
    public JSearchProcessRecord() {
        super(JSearchProcess.SEARCH_PROCESS);
    }

    /**
     * Create a detached, initialised JSearchProcessRecord
     */
    public JSearchProcessRecord(UUID processId, UUID requestId, String status, LocalDateTime created) {
        super(JSearchProcess.SEARCH_PROCESS);

        setProcessId(processId);
        setRequestId(requestId);
        setStatus(status);
        setCreated(created);
    }
}
