/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.search.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;
import org.systems.dipe.srs.search.jooq.tables.JSearchSquad;

import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JSearchSquadRecord extends TableRecordImpl<JSearchSquadRecord> implements Record3<UUID, UUID, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>searches.search_squad.squad_id</code>.
     */
    public JSearchSquadRecord setSquadId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>searches.search_squad.squad_id</code>.
     */
    public UUID getSquadId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>searches.search_squad.process_id</code>.
     */
    public JSearchSquadRecord setProcessId(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>searches.search_squad.process_id</code>.
     */
    public UUID getProcessId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>searches.search_squad.created</code>.
     */
    public JSearchSquadRecord setCreated(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>searches.search_squad.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, UUID, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<UUID, UUID, LocalDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return JSearchSquad.SEARCH_SQUAD.SQUAD_ID;
    }

    @Override
    public Field<UUID> field2() {
        return JSearchSquad.SEARCH_SQUAD.PROCESS_ID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return JSearchSquad.SEARCH_SQUAD.CREATED;
    }

    @Override
    public UUID component1() {
        return getSquadId();
    }

    @Override
    public UUID component2() {
        return getProcessId();
    }

    @Override
    public LocalDateTime component3() {
        return getCreated();
    }

    @Override
    public UUID value1() {
        return getSquadId();
    }

    @Override
    public UUID value2() {
        return getProcessId();
    }

    @Override
    public LocalDateTime value3() {
        return getCreated();
    }

    @Override
    public JSearchSquadRecord value1(UUID value) {
        setSquadId(value);
        return this;
    }

    @Override
    public JSearchSquadRecord value2(UUID value) {
        setProcessId(value);
        return this;
    }

    @Override
    public JSearchSquadRecord value3(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public JSearchSquadRecord values(UUID value1, UUID value2, LocalDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JSearchSquadRecord
     */
    public JSearchSquadRecord() {
        super(JSearchSquad.SEARCH_SQUAD);
    }

    /**
     * Create a detached, initialised JSearchSquadRecord
     */
    public JSearchSquadRecord(UUID squadId, UUID processId, LocalDateTime created) {
        super(JSearchSquad.SEARCH_SQUAD);

        setSquadId(squadId);
        setProcessId(processId);
        setCreated(created);
    }
}
