/*
 * This file is generated by jOOQ.
 */
package org.systems.dipe.srs.search.jooq.tables;


import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.systems.dipe.srs.search.jooq.Indexes;
import org.systems.dipe.srs.search.jooq.JSearches;
import org.systems.dipe.srs.search.jooq.Keys;
import org.systems.dipe.srs.search.jooq.tables.records.JSearchLocationRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JSearchLocation extends TableImpl<JSearchLocationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>searches.search_location</code>
     */
    public static final JSearchLocation SEARCH_LOCATION = new JSearchLocation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JSearchLocationRecord> getRecordType() {
        return JSearchLocationRecord.class;
    }

    /**
     * The column <code>searches.search_location.location_id</code>.
     */
    public final TableField<JSearchLocationRecord, UUID> LOCATION_ID = createField(DSL.name("location_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>searches.search_location.process_id</code>.
     */
    public final TableField<JSearchLocationRecord, UUID> PROCESS_ID = createField(DSL.name("process_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>searches.search_location.created</code>.
     */
    public final TableField<JSearchLocationRecord, LocalDateTime> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private JSearchLocation(Name alias, Table<JSearchLocationRecord> aliased) {
        this(alias, aliased, null);
    }

    private JSearchLocation(Name alias, Table<JSearchLocationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>searches.search_location</code> table reference
     */
    public JSearchLocation(String alias) {
        this(DSL.name(alias), SEARCH_LOCATION);
    }

    /**
     * Create an aliased <code>searches.search_location</code> table reference
     */
    public JSearchLocation(Name alias) {
        this(alias, SEARCH_LOCATION);
    }

    /**
     * Create a <code>searches.search_location</code> table reference
     */
    public JSearchLocation() {
        this(DSL.name("search_location"), null);
    }

    public <O extends Record> JSearchLocation(Table<O> child, ForeignKey<O, JSearchLocationRecord> key) {
        super(child, key, SEARCH_LOCATION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : JSearches.SEARCHES;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IX_SEARCHES_SEARCH_LOCATION_LOCATION_PROCESS);
    }

    @Override
    public List<ForeignKey<JSearchLocationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SEARCH_LOCATION__FK_SEARCHES_SEARCH_LOCATION_PROCESS);
    }

    private transient JSearchProcess _searchProcess;

    /**
     * Get the implicit join path to the <code>searches.search_process</code>
     * table.
     */
    public JSearchProcess searchProcess() {
        if (_searchProcess == null)
            _searchProcess = new JSearchProcess(this, Keys.SEARCH_LOCATION__FK_SEARCHES_SEARCH_LOCATION_PROCESS);

        return _searchProcess;
    }

    @Override
    public JSearchLocation as(String alias) {
        return new JSearchLocation(DSL.name(alias), this);
    }

    @Override
    public JSearchLocation as(Name alias) {
        return new JSearchLocation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public JSearchLocation rename(String name) {
        return new JSearchLocation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public JSearchLocation rename(Name name) {
        return new JSearchLocation(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<UUID, UUID, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
